/* This query fetches the total revenue generated by sales rep and the Managers team

1. Identified the sales rep individual total revenue
2. Identified the managers and ORG chart for all the employees using recursive CTE
3. Rolled up the total revenue at Manager level to get the total team revenue

*/

WITH employee_revenue AS (
    SELECT
        e.employee_id,
        COALESCE(Round(SUM(o.order_total),2), 0) AS own_revenue
    FROM dbo.dim_employee e
    LEFT JOIN dbo.fact_orders o
        ON e.employee_id = o.sales_rep_id
       AND o.order_status = 'Completed'
    GROUP BY e.employee_id
),

employee_tree AS (
    -- Each employee is in their own subtree
    SELECT
        employee_id AS manager_id,
        employee_id AS employee_id
    FROM dbo.dim_employee

    UNION ALL

    -- Find all descendants
    SELECT
        et.manager_id,
        e.employee_id
    FROM employee_tree et
    INNER JOIN dbo.dim_employee e
        ON e.manager_id = et.employee_id
)

SELECT
    m.employee_id,
    m.employee_name,
    m.role,
    SUM(er.own_revenue) AS team_total_revenue
FROM employee_tree et
INNER JOIN dbo.dim_employee m
    ON et.manager_id = m.employee_id
INNER JOIN employee_revenue er
    ON et.employee_id = er.employee_id
GROUP BY
    m.employee_id,
    m.employee_name,
    m.role
ORDER BY
    team_total_revenue DESC;
